theme: jekyll-theme-minimal
title: Nancy Connors # your name (or website title) here
logo: "headshot.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst | Lifelong Gamer | Data and Book Nerd
  <br>
  To get in touch, please reach out via <a href="https://www.linkedin.com/in/nancy-connors/">LinkedIn</a>
  <br>
  <br>
