# Site settings
title: Nancy McCoy - Data Analyst
email: nmccoy176@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "aurelila.github.io" # the base hostname & protocol for your site

linkedin_username: Nancy McCoy
github_username: Aurelila
kaggle_username: Aurelila

# Build settings
markdown: kramdown

remote_theme: jekyll-theme-creative
